sylius_mailer:
  emails:
    reference_invite:
      subject: "Reference Invite"
      template: "@EresSyliusReferralMarketingPlugin/Email/ReferenceInvite.html.twig"

sylius_promotion:
  resources:
    promotion_coupon:
      classes:
        model: Eres\SyliusReferralMarketingPlugin\Entity\PromotionCoupon
