workouse_referral_marketing_plugin_admin:
  resource: '@WorkouseReferralMarketingPlugin/Resources/config/admin_routing.yml'
  prefix: /admin

workouse_referral_marketing_plugin_shop:
  resource: '@WorkouseReferralMarketingPlugin/Resources/config/shop_routing.yml'
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
