workouse_referral_marketing_index:
  path: /account/referral-marketing/
  defaults:
    _controller: WorkouseReferralMarketingPlugin:Reference:index

workouse_referral_marketing_new:
  path: /account/referral-marketing/add
  defaults:
    _controller: WorkouseReferralMarketingPlugin:Reference:new

workouse_referral_marketing_check:
  path: /referral-marketing/{hash}.{_format}
  defaults:
    _controller: WorkouseReferralMarketingPlugin:Reference:check
  format: gif
  requirements:
    _format: gif|png|jpg|jpeg
